### ISSUE TITLE
Possible to get wether two meshes are intersecting or not ?? ( dont want to compute further ) )

### ISSUE THREAD

**Issue by shalinsirwani** [slyphiX/MeshIntersectionVolume#1]
Is it possible to just get if two meshes are intersecting or not , i dont need common volume , just 1 or 0 intersecting or not??

**Comment by lazyguyy** [comment]
I was also wondering the same. It appears that this individual who wrote the program isn't really interested in helping fellow computer scientists out; instead he is more interested in personal gain. Whatever, I'd recommend using a different program as this will most likely lead to nothing but unnecessary headaches...

**Comment by slyphix** [comment]
Sorry for the late reply. It is absolutely possible, but not using the provided interface. Since you do not need the actual intersection volume, you can just test all triangle pairs for intersections. If that fails you can test if one mesh is fully contained within the other. Most of the code structure will be the same, so feel free to fork and modify the code.

**Comment by lazyguyy** [comment]
OH WOW WHAT a rare SLYPHIX-REPLY???
Pack it up bois, we done here.
